/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPostRouteImport } from './routes/_authenticated/post'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated/my-listings'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedFavouritesRouteImport } from './routes/_authenticated/favourites'
import { Route as AuthenticatedExecutiveRouteImport } from './routes/_authenticated/executive'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedBiIndexRouteImport } from './routes/_authenticated/bi.index'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthenticatedBiTrustRouteImport } from './routes/_authenticated/bi.trust'
import { Route as AuthenticatedBiReportsRouteImport } from './routes/_authenticated/bi.reports'
import { Route as AuthenticatedBiInsightsRouteImport } from './routes/_authenticated/bi.insights'
import { Route as AuthenticatedBiCampaignsRouteImport } from './routes/_authenticated/bi.campaigns'
import { Route as ApiPublicCiRollupRouteImport } from './routes/api/public/ci/rollup'
import { Route as ApiPublicCiCCodeRouteImport } from './routes/api/public/ci/c.$code'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostRoute = AuthenticatedPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavouritesRoute = AuthenticatedFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExecutiveRoute = AuthenticatedExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedBiIndexRoute = AuthenticatedBiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMessagesRoute,
} as any)
const AuthenticatedBiTrustRoute = AuthenticatedBiTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedBiReportsRoute = AuthenticatedBiReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedBiInsightsRoute = AuthenticatedBiInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedBiRoute,
} as any)
const AuthenticatedBiCampaignsRoute =
  AuthenticatedBiCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedBiRoute,
  } as any)
const ApiPublicCiRollupRoute = ApiPublicCiRollupRouteImport.update({
  id: '/api/public/ci/rollup',
  path: '/api/public/ci/rollup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCiCCodeRoute = ApiPublicCiCCodeRouteImport.update({
  id: '/api/public/ci/c/$code',
  path: '/api/public/ci/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bi': typeof AuthenticatedBiRouteWithChildren
  '/business': typeof AuthenticatedBusinessRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/executive': typeof AuthenticatedExecutiveRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/post': typeof AuthenticatedPostRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/bi/campaigns': typeof AuthenticatedBiCampaignsRoute
  '/bi/insights': typeof AuthenticatedBiInsightsRoute
  '/bi/reports': typeof AuthenticatedBiReportsRoute
  '/bi/trust': typeof AuthenticatedBiTrustRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/bi/': typeof AuthenticatedBiIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/ci/rollup': typeof ApiPublicCiRollupRoute
  '/api/public/ci/c/$code': typeof ApiPublicCiCCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/executive': typeof AuthenticatedExecutiveRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/post': typeof AuthenticatedPostRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/bi/campaigns': typeof AuthenticatedBiCampaignsRoute
  '/bi/insights': typeof AuthenticatedBiInsightsRoute
  '/bi/reports': typeof AuthenticatedBiReportsRoute
  '/bi/trust': typeof AuthenticatedBiTrustRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/bi': typeof AuthenticatedBiIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/api/public/ci/rollup': typeof ApiPublicCiRollupRoute
  '/api/public/ci/c/$code': typeof ApiPublicCiCCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bi': typeof AuthenticatedBiRouteWithChildren
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/executive': typeof AuthenticatedExecutiveRoute
  '/_authenticated/favourites': typeof AuthenticatedFavouritesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/my-listings': typeof AuthenticatedMyListingsRoute
  '/_authenticated/post': typeof AuthenticatedPostRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/_authenticated/bi/campaigns': typeof AuthenticatedBiCampaignsRoute
  '/_authenticated/bi/insights': typeof AuthenticatedBiInsightsRoute
  '/_authenticated/bi/reports': typeof AuthenticatedBiReportsRoute
  '/_authenticated/bi/trust': typeof AuthenticatedBiTrustRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/bi/': typeof AuthenticatedBiIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/ci/rollup': typeof ApiPublicCiRollupRoute
  '/api/public/ci/c/$code': typeof ApiPublicCiCCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/community-guidelines'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/bi'
    | '/business'
    | '/campaigns'
    | '/executive'
    | '/favourites'
    | '/messages'
    | '/my-listings'
    | '/post'
    | '/profile'
    | '/business/$slug'
    | '/listing/$id'
    | '/seller/$id'
    | '/bi/campaigns'
    | '/bi/insights'
    | '/bi/reports'
    | '/bi/trust'
    | '/messages/$id'
    | '/bi/'
    | '/messages/'
    | '/api/public/ci/rollup'
    | '/api/public/ci/c/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/community-guidelines'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/business'
    | '/campaigns'
    | '/executive'
    | '/favourites'
    | '/my-listings'
    | '/post'
    | '/profile'
    | '/business/$slug'
    | '/listing/$id'
    | '/seller/$id'
    | '/bi/campaigns'
    | '/bi/insights'
    | '/bi/reports'
    | '/bi/trust'
    | '/messages/$id'
    | '/bi'
    | '/messages'
    | '/api/public/ci/rollup'
    | '/api/public/ci/c/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/community-guidelines'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/bi'
    | '/_authenticated/business'
    | '/_authenticated/campaigns'
    | '/_authenticated/executive'
    | '/_authenticated/favourites'
    | '/_authenticated/messages'
    | '/_authenticated/my-listings'
    | '/_authenticated/post'
    | '/_authenticated/profile'
    | '/business/$slug'
    | '/listing/$id'
    | '/seller/$id'
    | '/_authenticated/bi/campaigns'
    | '/_authenticated/bi/insights'
    | '/_authenticated/bi/reports'
    | '/_authenticated/bi/trust'
    | '/_authenticated/messages/$id'
    | '/_authenticated/bi/'
    | '/_authenticated/messages/'
    | '/api/public/ci/rollup'
    | '/api/public/ci/c/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  ListingIdRoute: typeof ListingIdRoute
  SellerIdRoute: typeof SellerIdRoute
  ApiPublicCiRollupRoute: typeof ApiPublicCiRollupRoute
  ApiPublicCiCCodeRoute: typeof ApiPublicCiCCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post': {
      id: '/_authenticated/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AuthenticatedPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-listings': {
      id: '/_authenticated/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favourites': {
      id: '/_authenticated/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AuthenticatedFavouritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive': {
      id: '/_authenticated/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof AuthenticatedExecutiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/bi/': {
      id: '/_authenticated/bi/'
      path: '/'
      fullPath: '/bi/'
      preLoaderRoute: typeof AuthenticatedBiIndexRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/bi/trust': {
      id: '/_authenticated/bi/trust'
      path: '/trust'
      fullPath: '/bi/trust'
      preLoaderRoute: typeof AuthenticatedBiTrustRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/bi/reports': {
      id: '/_authenticated/bi/reports'
      path: '/reports'
      fullPath: '/bi/reports'
      preLoaderRoute: typeof AuthenticatedBiReportsRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/bi/insights': {
      id: '/_authenticated/bi/insights'
      path: '/insights'
      fullPath: '/bi/insights'
      preLoaderRoute: typeof AuthenticatedBiInsightsRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/_authenticated/bi/campaigns': {
      id: '/_authenticated/bi/campaigns'
      path: '/campaigns'
      fullPath: '/bi/campaigns'
      preLoaderRoute: typeof AuthenticatedBiCampaignsRouteImport
      parentRoute: typeof AuthenticatedBiRoute
    }
    '/api/public/ci/rollup': {
      id: '/api/public/ci/rollup'
      path: '/api/public/ci/rollup'
      fullPath: '/api/public/ci/rollup'
      preLoaderRoute: typeof ApiPublicCiRollupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ci/c/$code': {
      id: '/api/public/ci/c/$code'
      path: '/api/public/ci/c/$code'
      fullPath: '/api/public/ci/c/$code'
      preLoaderRoute: typeof ApiPublicCiCCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBiRouteChildren {
  AuthenticatedBiCampaignsRoute: typeof AuthenticatedBiCampaignsRoute
  AuthenticatedBiInsightsRoute: typeof AuthenticatedBiInsightsRoute
  AuthenticatedBiReportsRoute: typeof AuthenticatedBiReportsRoute
  AuthenticatedBiTrustRoute: typeof AuthenticatedBiTrustRoute
  AuthenticatedBiIndexRoute: typeof AuthenticatedBiIndexRoute
}

const AuthenticatedBiRouteChildren: AuthenticatedBiRouteChildren = {
  AuthenticatedBiCampaignsRoute: AuthenticatedBiCampaignsRoute,
  AuthenticatedBiInsightsRoute: AuthenticatedBiInsightsRoute,
  AuthenticatedBiReportsRoute: AuthenticatedBiReportsRoute,
  AuthenticatedBiTrustRoute: AuthenticatedBiTrustRoute,
  AuthenticatedBiIndexRoute: AuthenticatedBiIndexRoute,
}

const AuthenticatedBiRouteWithChildren = AuthenticatedBiRoute._addFileChildren(
  AuthenticatedBiRouteChildren,
)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBiRoute: typeof AuthenticatedBiRouteWithChildren
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedExecutiveRoute: typeof AuthenticatedExecutiveRoute
  AuthenticatedFavouritesRoute: typeof AuthenticatedFavouritesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
  AuthenticatedPostRoute: typeof AuthenticatedPostRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBiRoute: AuthenticatedBiRouteWithChildren,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedExecutiveRoute: AuthenticatedExecutiveRoute,
  AuthenticatedFavouritesRoute: AuthenticatedFavouritesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
  AuthenticatedPostRoute: AuthenticatedPostRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  ListingIdRoute: ListingIdRoute,
  SellerIdRoute: SellerIdRoute,
  ApiPublicCiRollupRoute: ApiPublicCiRollupRoute,
  ApiPublicCiCCodeRoute: ApiPublicCiCCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
